language: 

before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

sudo: required

dist: trusty # Ubuntu 14.04.

compiler:
  - gcc

install: sh ./.travis/install-$TRAVIS_OS_NAME-deps.sh

addons:
  apt:
    packages:
      - cmake
      - lcov

matrix:
  include:
    - env:
      os: linux

#    - env:
#      os: osx

script: 
  - .travis/install-petsc.sh
  - export PETSC_DIR=$PWD/petsc; export PETSC_ARCH=petsc-arch
  - make codecov=1 V=1 
  - (cd demo; make V=1 codecov=1 )
  - (cd regression_tests; make test-mpfao)
  - (cd regression_tests; make test-steady)
  - (cd regression_tests; make test-steadyf90)
  - (cd regression_tests; make test-transient)
  - (cd regression_tests; make test-transient-mpfao)
  - cat regression_tests/*testlog
  - ls $PETSC_ARCH/obj/src/

after_success:
# Source: https://github.com/codecov/example-cpp11-cmake
 - lcov --capture --directory . --output-file coverage.info
#- lcov --remove coverage.info 'petsc-arch/*' --output-file coverage.info # filter system-files
 - lcov --list coverage.info # debug info
 - bash <(curl -s https://codecov.io/bash  -f coverage.info)

