#include <petsc.h>
#include <stdio.h>
#include <sys/stat.h>

// This function writes a self-contained Python script that can be used to
// inspect profiling results for TDycore.
PetscErrorCode TDyGenProfScript(const char* filename,
                                const char* csv_profile) {

  FILE* scriptFile = fopen(filename, "w");
  if (scriptFile == NULL)
    return -1;

  fprintf(scriptFile, "#!/usr/bin/env python3\n\n");

  // Write some descriptive comments to the script and usage information.
  fprintf(scriptFile, "# This script was autogenerated by TDycore using the -tdy_timers flag.\n");
  fprintf(scriptFile, "# You can run it with various options to inspect profiling results.\n\n");
  fprintf(scriptFile, "def usage():\n    print('%s: Usage:')\n", filename);
  fprintf(scriptFile, "    print('%s [command]\\n')\n", filename);
  fprintf(scriptFile, "    print('Commands are:')\n");
  fprintf(scriptFile, "    print('  topN - Show the N entries that take the most time.')\n");
  fprintf(scriptFile, "    exit()\n\n");

  // Read the contents of the CSV file so we can embed them in the script
  // itself.
  FILE* csvFile = fopen(csv_profile, "r");
  fseek(csvFile, 0, SEEK_END);
  size_t size = (size_t)ftell(csvFile);
  rewind(csvFile);
  char* csvData = malloc(sizeof(char) * size+1);
  size_t size_read = fread(csvData, 1, size, csvFile);
  csvData[size] = '\0';
  fclose(csvFile);
  fprintf(scriptFile, "# Here's the CSV data generated from the profiling run.\n");
  fprintf(scriptFile, "csv_data = '''");
  fprintf(scriptFile, "%s\n", csvData);
  fprintf(scriptFile, "'''\n\n");
  free(csvData);

  // Implement CSV data parsing.
  fprintf(scriptFile, "def parse_csv_data(csv_data):\n");
  fprintf(scriptFile, "    import io, csv\n");
  fprintf(scriptFile, "    with io.StringIO(csv_data) as f:\n");
  fprintf(scriptFile, "        data = csv.DictReader(f)\n");
  fprintf(scriptFile, "        rows = [r for r in data]\n");
  fprintf(scriptFile, "        return rows\n\n");

  // Implement the topN command.
  fprintf(scriptFile, "def topN(data, N):\n");
  fprintf(scriptFile, "    if len(data) == 0:\n        return\n");
  fprintf(scriptFile, "    print('tdyprof: showing top %%d hits:'%%N)\n");
  fprintf(scriptFile, "    columns = ['Stage Name', 'Event Name', 'Time', 'FLOP']\n");
  fprintf(scriptFile, "    print('{: >20} {: >40} {: >10} {: >16}'.format(*columns))\n");
  fprintf(scriptFile, "    sorted_rows = sorted(data, key = lambda row: float(row['Time']), reverse=True)\n");
  fprintf(scriptFile, "    for i in range(N):\n");
  fprintf(scriptFile, "        row = [sorted_rows[i][c][:40] for c in columns]\n");
  fprintf(scriptFile, "        print('{: >20} {: >40} {: >10} {: >16}'.format(*row))\n\n");

  // Now get down to business.
  fprintf(scriptFile, "import sys\n");
  fprintf(scriptFile, "def main():\n    if len(sys.argv) < 2:\n");
  fprintf(scriptFile, "        usage()\n\n");
  fprintf(scriptFile, "    data = parse_csv_data(csv_data)\n\n");
  fprintf(scriptFile, "    # Execute the given command.\n");
  fprintf(scriptFile, "    command = sys.argv[1]\n");
  fprintf(scriptFile, "    if command.startswith('top'):\n");
  fprintf(scriptFile, "        N = int(command[3:])\n");
  fprintf(scriptFile, "        topN(data, N)\n");

  fprintf(scriptFile, "if __name__ == '__main__':\n    main()\n");

  fclose(scriptFile);
  chmod(filename, S_IRWXU|S_IRGRP|S_IXGRP|S_IROTH|S_IXOTH);

  return 0;
}
